// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-C9HNSKT
// DateTime: 06.12.2020 15:36:35
// UserName: bosta
// Input file <SimpleYacc.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace SimpleParser
{
public enum Tokens {
    error=1,EOF=2,BEGIN=3,END=4,CYCLE=5,INUM=6,
    RNUM=7,ID=8,ASSIGN=9,SEMICOLON=10,COMMA=11,WHILE=12,
    DO=13,REPEAT=14,UNTIL=15,FOR=16,TO=17,WRITE=18,
    LEFT_BRACKET=19,RIGHT_BRACKET=20,IF=21,THEN=22,ELSE=23,VAR=24,
    PLUS=25,MINUS=26,MUL=27,DIVISION=28};

// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<int,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<int, LexLocation>
{
  // Verbatim content from SimpleYacc.y
// Ёти объ€влени€ добавл€ютс€ в класс GPPGParser, представл€ющий собой парсер, генерируемый системой gppg
    public Parser(AbstractScanner<int, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[36];
  private static State[] states = new State[70];
  private static string[] nonTerms = new string[] {
      "progr", "$accept", "block", "stlist", "statement", "assign", "cycle", 
      "while", "repeat", "for", "if", "write", "var", "identlist", "ident", "expr", 
      "T", "F", };

  static Parser() {
    states[0] = new State(new int[]{3,4},new int[]{-1,1,-3,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-4,5,-5,44,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[5] = new State(new int[]{4,6,10,7});
    states[6] = new State(-27);
    states[7] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-5,8,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[8] = new State(-4);
    states[9] = new State(-5);
    states[10] = new State(new int[]{9,11});
    states[11] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,12,-17,28,-18,27,-15,17});
    states[12] = new State(new int[]{25,13,26,23,4,-17,10,-17,15,-17,23,-17,17,-17});
    states[13] = new State(new int[]{8,18,6,19,19,20},new int[]{-17,14,-18,27,-15,17});
    states[14] = new State(new int[]{27,15,28,25,25,-19,26,-19,4,-19,10,-19,15,-19,23,-19,17,-19,20,-19,8,-19,3,-19,5,-19,12,-19,14,-19,16,-19,21,-19,18,-19,24,-19,13,-19,22,-19});
    states[15] = new State(new int[]{8,18,6,19,19,20},new int[]{-18,16,-15,17});
    states[16] = new State(-22);
    states[17] = new State(-24);
    states[18] = new State(-16);
    states[19] = new State(-25);
    states[20] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,21,-17,28,-18,27,-15,17});
    states[21] = new State(new int[]{20,22,25,13,26,23});
    states[22] = new State(-26);
    states[23] = new State(new int[]{8,18,6,19,19,20},new int[]{-17,24,-18,27,-15,17});
    states[24] = new State(new int[]{27,15,28,25,25,-20,26,-20,4,-20,10,-20,15,-20,23,-20,17,-20,20,-20,8,-20,3,-20,5,-20,12,-20,14,-20,16,-20,21,-20,18,-20,24,-20,13,-20,22,-20});
    states[25] = new State(new int[]{8,18,6,19,19,20},new int[]{-18,26,-15,17});
    states[26] = new State(-23);
    states[27] = new State(-21);
    states[28] = new State(new int[]{27,15,28,25,25,-18,26,-18,4,-18,10,-18,15,-18,23,-18,17,-18,20,-18,8,-18,3,-18,5,-18,12,-18,14,-18,16,-18,21,-18,18,-18,24,-18,13,-18,22,-18});
    states[29] = new State(-6);
    states[30] = new State(-7);
    states[31] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,32,-17,28,-18,27,-15,17});
    states[32] = new State(new int[]{25,13,26,23,8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-5,33,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[33] = new State(-28);
    states[34] = new State(-8);
    states[35] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,36,-17,28,-18,27,-15,17});
    states[36] = new State(new int[]{13,37,25,13,26,23});
    states[37] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-5,38,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[38] = new State(-29);
    states[39] = new State(-9);
    states[40] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-4,41,-5,44,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[41] = new State(new int[]{15,42,10,7});
    states[42] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,43,-17,28,-18,27,-15,17});
    states[43] = new State(new int[]{25,13,26,23,4,-30,10,-30,15,-30,23,-30});
    states[44] = new State(-3);
    states[45] = new State(-10);
    states[46] = new State(new int[]{8,18},new int[]{-6,47,-15,10});
    states[47] = new State(new int[]{17,48});
    states[48] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,49,-17,28,-18,27,-15,17});
    states[49] = new State(new int[]{13,50,25,13,26,23});
    states[50] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-5,51,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[51] = new State(-31);
    states[52] = new State(-11);
    states[53] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,54,-17,28,-18,27,-15,17});
    states[54] = new State(new int[]{22,55,25,13,26,23});
    states[55] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-5,56,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[56] = new State(new int[]{23,57,4,-33,10,-33,15,-33});
    states[57] = new State(new int[]{8,18,3,4,5,31,12,35,14,40,16,46,21,53,18,60,24,65},new int[]{-5,58,-6,9,-15,10,-3,29,-7,30,-8,34,-9,39,-10,45,-11,52,-12,59,-13,64});
    states[58] = new State(-34);
    states[59] = new State(-12);
    states[60] = new State(new int[]{19,61});
    states[61] = new State(new int[]{8,18,6,19,19,20},new int[]{-16,62,-17,28,-18,27,-15,17});
    states[62] = new State(new int[]{20,63,25,13,26,23});
    states[63] = new State(-32);
    states[64] = new State(-13);
    states[65] = new State(new int[]{8,18},new int[]{-14,66,-15,69});
    states[66] = new State(new int[]{11,67,4,-35,10,-35,15,-35,23,-35});
    states[67] = new State(new int[]{8,18},new int[]{-15,68});
    states[68] = new State(-15);
    states[69] = new State(-14);

    rules[1] = new Rule(-2, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-4, new int[]{-5});
    rules[4] = new Rule(-4, new int[]{-4,10,-5});
    rules[5] = new Rule(-5, new int[]{-6});
    rules[6] = new Rule(-5, new int[]{-3});
    rules[7] = new Rule(-5, new int[]{-7});
    rules[8] = new Rule(-5, new int[]{-8});
    rules[9] = new Rule(-5, new int[]{-9});
    rules[10] = new Rule(-5, new int[]{-10});
    rules[11] = new Rule(-5, new int[]{-11});
    rules[12] = new Rule(-5, new int[]{-12});
    rules[13] = new Rule(-5, new int[]{-13});
    rules[14] = new Rule(-14, new int[]{-15});
    rules[15] = new Rule(-14, new int[]{-14,11,-15});
    rules[16] = new Rule(-15, new int[]{8});
    rules[17] = new Rule(-6, new int[]{-15,9,-16});
    rules[18] = new Rule(-16, new int[]{-17});
    rules[19] = new Rule(-16, new int[]{-16,25,-17});
    rules[20] = new Rule(-16, new int[]{-16,26,-17});
    rules[21] = new Rule(-17, new int[]{-18});
    rules[22] = new Rule(-17, new int[]{-17,27,-18});
    rules[23] = new Rule(-17, new int[]{-17,28,-18});
    rules[24] = new Rule(-18, new int[]{-15});
    rules[25] = new Rule(-18, new int[]{6});
    rules[26] = new Rule(-18, new int[]{19,-16,20});
    rules[27] = new Rule(-3, new int[]{3,-4,4});
    rules[28] = new Rule(-7, new int[]{5,-16,-5});
    rules[29] = new Rule(-8, new int[]{12,-16,13,-5});
    rules[30] = new Rule(-9, new int[]{14,-4,15,-16});
    rules[31] = new Rule(-10, new int[]{16,-6,17,-16,13,-5});
    rules[32] = new Rule(-12, new int[]{18,19,-16,20});
    rules[33] = new Rule(-11, new int[]{21,-16,22,-5});
    rules[34] = new Rule(-11, new int[]{21,-16,22,-5,23,-5});
    rules[35] = new Rule(-13, new int[]{24,-14});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
